services:
  service_db:
    image: mysql:5.7
    volumes:
      - ./src/mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: storeuvm_db
      MYSQL_ROOT_USER: uadmin
      MYSQL_USER: uadmin
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
